# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20150316_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='series',
            name='tvdbid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
