# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160307_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='air_date',
            new_name='air_date_tmp',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='first_aired',
            new_name='first_aired_tmp',
        ),
    ]
