# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160307_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='air_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='first_aired',
            field=models.DateField(null=True),
        ),
    ]
