# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:05
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160307_2205'),
    ]

    operations = [
    ]
