# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160307_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='air_date_tmp',
        ),
        migrations.RemoveField(
            model_name='series',
            name='first_aired_tmp',
        ),
    ]
