# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160307_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastupdate',
            old_name='date',
            new_name='datetime',
        ),
    ]
