# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160309_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.Series'),
        ),
    ]
