# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:59
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    Series = apps.get_model("core", "Series")
    for series in Series.objects.all():
        for season in series.seasons.all():
            for episode in season.episodes.all():
                episode.series = season.series
                episode.season_number = season.number
                episode.save()

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160309_1659'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
