# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160309_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.AlterField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.Series'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
