# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160309_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='season_number',
            new_name='season',
        ),
    ]
