# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160309_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season', 'episode']},
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='number',
            new_name='episode',
        ),
    ]
