# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_series_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='banner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='imdb',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
