# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20160310_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
