# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_series_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', ''), ('default', ''), ('archived', '')], default='default', max_length=255)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
