# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:24
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserSeries = apps.get_model("core", "UserSeries")
    Series = apps.get_model("core", "Series")

    user = User.objects.get(username='kvikshaug')
    for series in Series.objects.all():
        UserSeries.objects.create(
            user=user,
            series=series,
            last_seen=series.last_seen,
            status=series.local_status,
        )

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userseries'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
