# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160311_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='series',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='series',
            name='local_status',
        ),
    ]
