# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_auto_20160311_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userseries',
            new_name='watching',
        ),
    ]
